name: Main

on:
  push:
  schedule:
  - cron: '52 3 4 * *'
env:
  ARTIFACT: postgres-query-error-demo
  JAVA_VERSION: 17

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJSON(github) }}
      run: echo "$GITHUB_CONTEXT"
    - name: Dump job context
      env:
        JOB_CONTEXT: ${{ toJSON(job) }}
      run: echo "$JOB_CONTEXT"
    - name: Dump steps context
      env:
        STEPS_CONTEXT: ${{ toJSON(steps) }}
      run: echo "$STEPS_CONTEXT"
    - name: Dump runner context
      env:
        RUNNER_CONTEXT: ${{ toJSON(runner) }}
      run: echo "$RUNNER_CONTEXT"
    - name: Dump strategy context
      env:
        STRATEGY_CONTEXT: ${{ toJSON(strategy) }}
      run: echo "$STRATEGY_CONTEXT"
    - name: Dump matrix context
      env:
        MATRIX_CONTEXT: ${{ toJSON(matrix) }}
      run: echo "$MATRIX_CONTEXT"
  version:
    runs-on: ubuntu-latest
    outputs:
      new_version: ${{ steps.output.outputs.new_version }}
    steps:
    - uses: actions/checkout@v3.2.0
      with:
        # fetch entire history to analyze commits since last tag
        fetch-depth: 0
    - name: Bump version and push tag
      id: tag
      if: ${{ github.ref == 'refs/heads/master' || github.ref == 'refs/heads/main' }}
      uses: mathieudutour/github-tag-action@v6.1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        release_branches: master,main
    - id: output
      env:
        NEW_VERSION: ${{ steps.tag.outputs.new_version}}
      run: |
        echo "new_version=${NEW_VERSION:-$GITHUB_SHA}" >> $GITHUB_OUTPUT
    - name: Make sure build did not change anything
      run: git diff --exit-code
  macos:
    runs-on: macos-latest
    needs: version
    env:
      REVISION: ${{ needs.version.outputs.new_version }}
    steps:
    - uses: actions/checkout@v3.2.0
    - uses: actions/setup-java@v3.8.0
      with:
        java-version: ${{ env.JAVA_VERSION }}
        distribution: temurin
        cache: 'maven'
    - name: setup docker, colima and testcontainers
      run: |
        set -o xtrace
        brew install docker docker-compose
        mkdir -p ~/.docker/cli-plugins
        ln -sfn /usr/local/opt/docker-compose/bin/docker-compose ~/.docker/cli-plugins/docker-compose
        colima start --cpu 2 --memory 7
        echo "TESTCONTAINERS_DOCKER_SOCKET_OVERRIDE=/var/run/docker.sock" >> $GITHUB_ENV
        echo "DOCKER_HOST=unix://${HOME}/.colima/docker.sock" >> $GITHUB_ENV
    - name: Build with Maven
      run: |
        set -o xtrace
        docker compose up --detach
        ./mvnw \
          --batch-mode \
          -Dsha1="${GITHUB_SHA}" \
          -Drevision="${REVISION}" \
          verify
        docker compose down
    - name: Move artifacts
      run: |
        mkdir target/artifacts
        cp target/${{ env.ARTIFACT }}-* target/artifacts
    - uses: actions/upload-artifact@v3.1.1
      with:
        name: ${{ env.ARTIFACT }}-${{ github.job }}-${{ needs.version.outputs.new_version }}
        path: target/artifacts
    - name: Make sure build did not change anything
      run: git diff --exit-code
  linux:
    runs-on: ubuntu-latest
    needs: version
    env:
      REVISION: ${{ needs.version.outputs.new_version }}
    steps:
    - uses: actions/checkout@v3.2.0
    - uses: actions/setup-java@v3.8.0
      with:
        java-version: ${{ env.JAVA_VERSION }}
        distribution: temurin
        cache: 'maven'
    - name: Build with Maven
      run: |
        set -o xtrace
        docker compose up --detach
        ./mvnw \
          --batch-mode \
          -Dsha1="${GITHUB_SHA}" \
          -Drevision="${REVISION}" \
          verify
        docker compose down
    - name: Move artifacts
      run: |
        mkdir target/artifacts
        cp target/${{ env.ARTIFACT }}-* target/artifacts
    - uses: actions/upload-artifact@v3.1.1
      with:
        name: ${{ env.ARTIFACT }}-${{ github.job }}-${{ needs.version.outputs.new_version }}
        path: target/artifacts
    - name: Make sure build did not change anything
      run: git diff --exit-code
